packages:
  - '.'
minimumReleaseAgeExclude:
  - happy-dom@20.12.2
  - '@vitest/mocker@5.0.1'
  - '@vitest/spy@5.0.1'
  - vitest@5.0.1
  - '@rslint/core@0.9.3'
  - '@rslint/native-darwin-arm64@0.9.3'
  - '@rslint/native-darwin-x64@0.9.3'
  - '@rslint/native-linux-arm64-gnu@0.9.3'
  - '@rslint/native-linux-arm64-musl@0.9.3'
  - '@rslint/native-linux-x64-gnu@0.9.3'
  - '@rslint/native-linux-x64-musl@0.9.3'
  - '@rslint/native-win32-arm64-msvc@0.9.3'
  - '@rslint/native-win32-x64-msvc@0.9.3'
  - '@oxfmt/binding-android-arm-eabi@0.70.0'
  - '@oxfmt/binding-android-arm64@0.70.0'
  - '@oxfmt/binding-darwin-arm64@0.70.0'
  - '@oxfmt/binding-darwin-x64@0.70.0'
  - '@oxfmt/binding-freebsd-x64@0.70.0'
  - '@oxfmt/binding-linux-arm-gnueabihf@0.70.0'
  - '@oxfmt/binding-linux-arm-musleabihf@0.70.0'
  - '@oxfmt/binding-linux-arm64-gnu@0.70.0'
  - '@oxfmt/binding-linux-arm64-musl@0.70.0'
  - '@oxfmt/binding-linux-ppc64-gnu@0.70.0'
  - '@oxfmt/binding-linux-riscv64-gnu@0.70.0'
  - '@oxfmt/binding-linux-riscv64-musl@0.70.0'
  - '@oxfmt/binding-linux-s390x-gnu@0.70.0'
  - '@oxfmt/binding-linux-x64-gnu@0.70.0'
  - '@oxfmt/binding-linux-x64-musl@0.70.0'
  - '@oxfmt/binding-openharmony-arm64@0.70.0'
  - '@oxfmt/binding-win32-arm64-msvc@0.70.0'
  - '@oxfmt/binding-win32-ia32-msvc@0.70.0'
  - '@oxfmt/binding-win32-x64-msvc@0.70.0'
  - oxfmt@0.70.0
